version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-books-search
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge